//
// Created by ravyu on 28/11/20.
//

#ifndef FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ITEM_INTERACTION_SCREEN_H_
#define FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ITEM_INTERACTION_SCREEN_H_

class ItemInteractionScreen {

};

#endif //FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ITEM_INTERACTION_SCREEN_H_
