//
// Created by ravyu on 28/11/20.
//

#ifndef FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ROOM_SCREEN_H_
#define FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ROOM_SCREEN_H_

class RoomScreen {

};

#endif //FINAL_PROJECT_RAVYUS_INCLUDE_GUI_SCREENS_ROOM_SCREEN_H_
