//
// Created by ravyu on 28/11/20.
//

#ifndef FINAL_PROJECT_RAVYUS_INCLUDE_GUI_INVENTORY_MANAGER_H_
#define FINAL_PROJECT_RAVYUS_INCLUDE_GUI_INVENTORY_MANAGER_H_

class inventory_manager {

};

#endif //FINAL_PROJECT_RAVYUS_INCLUDE_GUI_INVENTORY_MANAGER_H_
