//
// Created by ravyu on 28/11/20.
//

#ifndef FINAL_PROJECT_RAVYUS_INCLUDE_GUI_NAVIGATION_MANAGER_H_
#define FINAL_PROJECT_RAVYUS_INCLUDE_GUI_NAVIGATION_MANAGER_H_

class NavigationManager {

};

#endif //FINAL_PROJECT_RAVYUS_INCLUDE_GUI_NAVIGATION_MANAGER_H_
